# Config for https://github.com/apps/release-drafter
name-template: 'v$NEXT_MINOR_VERSION (🌈 Insert Release Name)'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'Dependency Updates'
    label: 'dependencies'
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
exclude-labels:
  - 'skip-changelog'
autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    body:
      - '/feature{0,1}\/.+/'
template: |
  ## Changes
  $CHANGES
  ## Upgrading
  To upgrade, update your `pipeline.yml` files:
  ```diff
  steps:
    - plugins:
  -     jack1902/sonarscanner#$PREVIOUS_TAG:
  +     jack1902/sonarscanner#v$NEXT_MINOR_VERSION:
          project_key: "PLACEHOLDER"
  ```
